In [1]:
import fastf1
import pandas as pd
fastf1.Cache.enable_cache("../data/cache")

In [2]:
sessione = fastf1.get_session(2024, "Monza", "R")
sessione.load()

core           INFO 	Loading data for Italian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['16', '81', '4', '55', '44', '1', '63', '11', '23', '20', '14', '43', '3', '31', '10', '77', '27', '24', '18', '22']

In [3]:
giri = sessione.laps
giri.head()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 00:57:18.931000,LEC,16,0 days 00:01:28.179000,1.0,1.0,NaT,NaT,NaT,0 days 00:00:29.989000,...,True,Ferrari,0 days 00:55:50.494000,2024-09-01 13:03:34.413,1,2.0,False,,False,False
1,0 days 00:58:44.327000,LEC,16,0 days 00:01:25.396000,2.0,1.0,NaT,NaT,0 days 00:00:27.707000,0 days 00:00:29.265000,...,True,Ferrari,0 days 00:57:18.931000,2024-09-01 13:05:02.850,1,2.0,False,,False,True
2,0 days 01:00:09.506000,LEC,16,0 days 00:01:25.179000,3.0,1.0,NaT,NaT,0 days 00:00:27.679000,0 days 00:00:29.001000,...,True,Ferrari,0 days 00:58:44.327000,2024-09-01 13:06:28.246,1,2.0,False,,False,True
3,0 days 01:01:34.316000,LEC,16,0 days 00:01:24.810000,4.0,1.0,NaT,NaT,0 days 00:00:27.653000,0 days 00:00:28.883000,...,True,Ferrari,0 days 01:00:09.506000,2024-09-01 13:07:53.425,1,2.0,False,,False,True
4,0 days 01:02:58.919000,LEC,16,0 days 00:01:24.603000,5.0,1.0,NaT,NaT,0 days 00:00:27.630000,0 days 00:00:28.790000,...,True,Ferrari,0 days 01:01:34.316000,2024-09-01 13:09:18.235,1,2.0,False,,False,True

In [4]:
giri.columns

Index(['Time', 'Driver', 'DriverNumber', 'LapTime', 'LapNumber', 'Stint',
       'PitOutTime', 'PitInTime', 'Sector1Time', 'Sector2Time', 'Sector3Time',
       'Sector1SessionTime', 'Sector2SessionTime', 'Sector3SessionTime',
       'SpeedI1', 'SpeedI2', 'SpeedFL', 'SpeedST', 'IsPersonalBest',
       'Compound', 'TyreLife', 'FreshTyre', 'Team', 'LapStartTime',
       'LapStartDate', 'TrackStatus', 'Position', 'Deleted', 'DeletedReason',
       'FastF1Generated', 'IsAccurate'],
      dtype='object')

In [5]:
giri.dtypes

Time                  timedelta64[ns]
Driver                         object
DriverNumber                   object
LapTime               timedelta64[ns]
LapNumber                     float64
Stint                         float64
PitOutTime            timedelta64[ns]
PitInTime             timedelta64[ns]
Sector1Time           timedelta64[ns]
Sector2Time           timedelta64[ns]
Sector3Time           timedelta64[ns]
Sector1SessionTime    timedelta64[ns]
Sector2SessionTime    timedelta64[ns]
Sector3SessionTime    timedelta64[ns]
SpeedI1                       float64
SpeedI2                       float64
SpeedFL                       float64
SpeedST                       float64
IsPersonalBest                   bool
Compound                       object
TyreLife                      float64
FreshTyre                        bool
Team                           object
LapStartTime          timedelta64[ns]
LapStartDate           datetime64[ns]
TrackStatus                    object
Position                      float64
Deleted                          bool
DeletedReason                  object
FastF1Generated                  bool
IsAccurate                       bool
dtype: object

In [6]:
ham = giri.pick_drivers("HAM")
ham[["LapNumber", "LapTime", "Compound", "TyreLife"]].head(10)

     LapNumber                LapTime Compound  TyreLife
212        1.0 0 days 00:01:29.674000   MEDIUM       1.0
213        2.0 0 days 00:01:26.043000   MEDIUM       2.0
214        3.0 0 days 00:01:25.630000   MEDIUM       3.0
215        4.0 0 days 00:01:25.722000   MEDIUM       4.0
216        5.0 0 days 00:01:24.771000   MEDIUM       5.0
217        6.0 0 days 00:01:24.919000   MEDIUM       6.0
218        7.0 0 days 00:01:25.205000   MEDIUM       7.0
219        8.0 0 days 00:01:24.871000   MEDIUM       8.0
220        9.0 0 days 00:01:25.035000   MEDIUM       9.0
221       10.0 0 days 00:01:24.909000   MEDIUM      10.0

In [7]:
print(len(sessione.laps))

1008

In [8]:
ham_laps = sessione.laps.pick_drivers("HAM")
print(len(ham_laps))

53

Quante righe ha la tabella giri? Dell'intera sessione a Monza 1008 righe, Hamilton invece ha percorso 53 giri (53 righe).
Di che tipo è la colonna LapTime? timedelta64[ns]
Quali colonne serviranno per il grafico degli stint e delle mescole? La colonna Stint di tipo float64 e la colonna Compound di tipo object e TyreLife di tipo float64

In [15]:
type(giri)

fastf1.core.Laps

In [21]:
giri.Driver.nunique()

20

In [22]:
giri["Driver"].value_counts()

Driver
LEC    53
PIA    53
NOR    53
SAI    53
HAM    53
VER    53
RUS    53
PER    53
ALB    53
MAG    53
ALO    53
COL    53
RIC    53
OCO    52
GAS    52
BOT    52
HUL    52
ZHO    52
STR    52
TSU     7
Name: count, dtype: int64

In [23]:
giri["IsAccurate"].value_counts()

IsAccurate
True     927
False     81
Name: count, dtype: int64

Quanti piloti ci sono nella colonna Driver, e perché non tutti hanno lo stesso numero di giri? Ci sono 20 piloti, e non tutti hanno lo stesso numero di giri a causa di possibili incidenti o problemi alla vettura o doppiati
Nella tabella compaiono dei NaT. Cosa significano, e in quali righe sono presenti? Signfica Not a Time, ossia un dato mancante, sono presenti in PitInTime, PitOutTime, Sector1Time.
Guardando IsAccurate e Deleted. Tutti i giri sono adatti per calcolare un tempo medio? No 81 giri non sono adatti per calcolare un tempo medio, ossia l'8% del totale.